export enum ErrorCode {
  PERMISSION_DENIED = 'Bạn không đủ quyền để thực hiện',
  ROLE_CODE_DUPLICATE = 'Trùng role code',
  CUSTOMER_DUPLICATE_PHONE = 'Trùng phone',
  CUSTOMER_DUPLICATE_EMAIL = 'Trùng email',
  CITY_NOT_FOUND = 'Không tìn thấy thành phố',
  VALUE_ZERO = 'Giá trị không được nhỏ hơn 0',
  USERNAME_EXISTS = 'Tài khoản đã tồn tại',
  EMAIL_NOT_EXISTS = 'Email không tồn tại',
  USER_NOT_EXISTS = 'Tài khoản không tồn tại',
  ACCOUNT_NOT_EXISTS = 'Tài khoản không tồn tại',
  TOKEN_INVALID = 'Token không chính xác.',
  TOKEN_EXPIRED = 'Token đã hết hạn.',
  TOKEN_NOT_FOUND = 'Không tìm thấy token',
  TOKEN_CAN_NOT_ACTIVE = 'Token không thể kích hoạt',
  ACCOUNT_ALREADY_ACTIVED = 'Bạn đã quá hạn kích hoạt',
  EMAIL_INVALID = 'email_invalid',
  ACCOUNT_PASSWORD_INVALID = 'Tài khoản hoặc mật khẩu không chính xác',
  ACCOUNT_NOT_ACTIVE = 'Tài khoản của bạn chưa kích hoạt',
  ACCOUNT_NOT_APPROVED = 'Tài khoản của bạn không được duyệt',
  ACCOUNT_DISABLED = 'Tài khoản đã bị vô hiệu hóa',
  PASSWORD_INVALID = 'Mật khẩu không đúng',
  ACCOUNT_EXIST = 'username exist',
  USERNAME_INVALID = 'username_invalid',

  USER_ACTIVED = 'Tài khoản đã được kích hoạt',

  PHONE_EXISTS = 'Phone đã tồn tại',
  EMAIL_EXISTS = 'Email đã tồn tại',
  ESTATE_EXISTS = 'Đối tượng không tồn tại',
  ESTATE_DUPLICATE = 'Trùng estate id',
}
